require(quantmod)
getSymbols('BAC')
plot(Cl(BAC), col = 'black')
head(BAC)
head(Ad(BAC))
barChart(BAC)
addTA(EMA(Cl(BAC)), on = 1, col = 6)
getSymbols('YHOO', src = 'google')
getSymbols('GOOG', src = 'yahoo')
barChart(YHOO)
require(TTR)
candleChart(GOOG, multi.col=TRUE, theme = 'white', subset = 'last 4 months')
chartSeries(YHOO, subset = 'last 5 months', theme = 'white')
addMACD()
addBBands()
